/* Main Simulation File */
/* Simulation code for ExternalLibraries_working generated by the OpenModelica Compiler v1.9.3. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "ExternalLibraries_working_functions.h"
#include "ExternalLibraries_working_model.h"
#include "ExternalLibraries_working_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define prefixedName_performSimulation ExternalLibraries_working_performSimulation
#define prefixedName_updateContinuousSystem ExternalLibraries_working_updateContinuousSystem
#include <simulation/solver/perform_simulation.c>

#define prefixedName_performQSSSimulation ExternalLibraries_working_performQSSSimulation
#include <simulation/solver/perform_qss_simulation.c>

/* dummy VARINFO and FILEINFO */
const FILE_INFO dummyFILE_INFO = omc_dummyFileInfo;
const VAR_INFO dummyVAR_INFO = omc_dummyVarInfo;
#if defined(__cplusplus)
extern "C" {
#endif
int measure_time_flag = 0;

int ExternalLibraries_working_input_function(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}

int ExternalLibraries_working_input_function_init(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}


int ExternalLibraries_working_output_function(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}


/*
 equation index: 3
 type: SIMPLE_ASSIGN
 der(y) = -ExternalLibraries_working.ExternalFunc2(y)
 */
void ExternalLibraries_working_eqFunction_3(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,3};
  $P$DER$Py = (-omc_ExternalLibraries__working_ExternalFunc2(threadData, $Py));
  TRACE_POP
}


int ExternalLibraries_working_functionDAE(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  int equationIndexes[1] = {0};
  
  data->simulationInfo.needToIterate = 0;
  data->simulationInfo.discreteCall = 1;
  ExternalLibraries_working_eqFunction_3(data, threadData);
  data->simulationInfo.discreteCall = 0;
  
  TRACE_POP
  return 0;
}

int ExternalLibraries_working_symEulerUpdate(DATA *data, modelica_real dt)
{
  TRACE_PUSH
  #ifdef $P__OMC_DT
    $P__OMC_DT = dt;
  #else
    return -1;
  #endif
  
  TRACE_POP
  return 0;
}



/* forwarded equations */
extern void ExternalLibraries_working_eqFunction_3(DATA* data, threadData_t *threadData);

static void functionODE_system0(DATA *data, threadData_t *threadData)
{
  ExternalLibraries_working_eqFunction_3(data, threadData);
}

int ExternalLibraries_working_functionODE(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  data->simulationInfo.callStatistics.functionODE++;
  
  functionODE_system0(data, threadData);

  
  TRACE_POP
  return 0;
}

/* forward the main in the simulation runtime */
extern int _main_SimulationRuntime(int argc, char**argv, DATA *data, threadData_t *threadData);

#include "ExternalLibraries_working_12jac.h"
#include "ExternalLibraries_working_13opt.h"

struct OpenModelicaGeneratedFunctionCallbacks ExternalLibraries_working_callback = {
   (int (*)(DATA *, threadData_t *, void *)) ExternalLibraries_working_performSimulation,
   (int (*)(DATA *, threadData_t *, void *)) ExternalLibraries_working_performQSSSimulation,
   ExternalLibraries_working_updateContinuousSystem,
   ExternalLibraries_working_callExternalObjectConstructors,
   ExternalLibraries_working_callExternalObjectDestructors,
   ExternalLibraries_working_initialNonLinearSystem,
   ExternalLibraries_working_initialLinearSystem,
   ExternalLibraries_working_initialMixedSystem,
   ExternalLibraries_working_initializeStateSets,
   ExternalLibraries_working_functionODE,
   ExternalLibraries_working_functionAlgebraics,
   ExternalLibraries_working_functionDAE,
   ExternalLibraries_working_input_function,
   ExternalLibraries_working_input_function_init,
   ExternalLibraries_working_output_function,
   ExternalLibraries_working_function_storeDelayed,
   ExternalLibraries_working_updateBoundVariableAttributes,
   0 /* useHomotopy */,
   ExternalLibraries_working_functionInitialEquations,
   ExternalLibraries_working_functionRemovedInitialEquations,
   ExternalLibraries_working_updateBoundParameters,
   ExternalLibraries_working_checkForAsserts,
   ExternalLibraries_working_function_ZeroCrossingsEquations,
   ExternalLibraries_working_function_ZeroCrossings,
   ExternalLibraries_working_function_updateRelations,
   ExternalLibraries_working_checkForDiscreteChanges,
   ExternalLibraries_working_zeroCrossingDescription,
   ExternalLibraries_working_relationDescription,
   ExternalLibraries_working_function_initSample,
   ExternalLibraries_working_INDEX_JAC_A,
   ExternalLibraries_working_INDEX_JAC_B,
   ExternalLibraries_working_INDEX_JAC_C,
   ExternalLibraries_working_INDEX_JAC_D,
   ExternalLibraries_working_initialAnalyticJacobianA,
   ExternalLibraries_working_initialAnalyticJacobianB,
   ExternalLibraries_working_initialAnalyticJacobianC,
   ExternalLibraries_working_initialAnalyticJacobianD,
   ExternalLibraries_working_functionJacA_column,
   ExternalLibraries_working_functionJacB_column,
   ExternalLibraries_working_functionJacC_column,
   ExternalLibraries_working_functionJacD_column,
   ExternalLibraries_working_linear_model_frame,
   ExternalLibraries_working_mayer,
   ExternalLibraries_working_lagrange,
   ExternalLibraries_working_pickUpBoundsForInputsInOptimization,
   ExternalLibraries_working_setInputData,
   ExternalLibraries_working_getTimeGrid,
   ExternalLibraries_working_symEulerUpdate,
   ExternalLibraries_working_function_initSynchronous,
   ExternalLibraries_working_function_updateSynchronous,
   ExternalLibraries_working_function_equationsSynchronous

};

void ExternalLibraries_working_setupDataStruc(DATA *data, threadData_t *threadData)
{
  assertStreamPrint(threadData,0!=data, "Error while initialize Data");
  data->callback = &ExternalLibraries_working_callback;
  data->modelData.modelName = "ExternalLibraries_working";
  data->modelData.modelFilePrefix = "ExternalLibraries_working";
  data->modelData.resultFileName = NULL;
  data->modelData.modelDir = "C:/Users/fishes3/Dropbox/FMU/Passing_Data_Testing/Example";
  data->modelData.modelGUID = "{8c4e810f-3df3-4a00-8276-176fa3c9f9e0}";
  #ifdef OPENMODELICA_XML_FROM_FILE_AT_RUNTIME
  data->modelData.initXMLData = NULL;
  data->modelData.modelDataXml.infoXMLData = NULL;
  #else
  data->modelData.initXMLData =
  #include "ExternalLibraries_working_init.c"
  ;
  data->modelData.modelDataXml.infoXMLData =
  #include "ExternalLibraries_working_info.c"
  ;
  #endif
  
  data->modelData.nStates = 1;
  data->modelData.nVariablesReal = 2*1+0+0+0 + 0;
  data->modelData.nDiscreteReal = 0;
  data->modelData.nVariablesInteger = 0;
  data->modelData.nVariablesBoolean = 0;
  data->modelData.nVariablesString = 0;
  data->modelData.nParametersReal = 0;
  data->modelData.nParametersInteger = 0;
  data->modelData.nParametersBoolean = 0;
  data->modelData.nParametersString = 0;
  data->modelData.nInputVars = 0;
  data->modelData.nOutputVars = 0;
  
  data->modelData.nAliasReal = 0;
  data->modelData.nAliasInteger = 0;
  data->modelData.nAliasBoolean = 0;
  data->modelData.nAliasString = 0;
  
  data->modelData.nZeroCrossings = 0;
  data->modelData.nSamples = 0;
  data->modelData.nRelations = 0;
  data->modelData.nMathEvents = 0;
  data->modelData.nExtObjs = 0;
  setupModelInfoFunctions(1);
  data->modelData.modelDataXml.fileName = "ExternalLibraries_working_info.json";
  data->modelData.modelDataXml.modelInfoXmlLength = 0;
  data->modelData.modelDataXml.nFunctions = 1;
  data->modelData.modelDataXml.nProfileBlocks = 0;
  data->modelData.modelDataXml.nEquations = 4;
  data->modelData.nMixedSystems = 0;
  data->modelData.nLinearSystems = 0;
  data->modelData.nNonLinearSystems = 0;
  data->modelData.nStateSets = 0;
  data->modelData.nJacobians = 4;
  data->modelData.nOptimizeConstraints = 0;
  data->modelData.nOptimizeFinalConstraints = 0;
  
  data->modelData.nDelayExpressions = 0;
  
  data->modelData.nClocks = 0;
  data->modelData.nSubClocks = 0;
  
}

#ifdef __cplusplus
}
#endif

static int rml_execution_failed()
{
  fflush(NULL);
  fprintf(stderr, "Execution failed!\n");
  fflush(NULL);
  return 1;
}

#if defined(threadData)
#undef threadData
#endif
/* call the simulation runtime main from our main! */
int main(int argc, char**argv)
{
  int res;
  DATA simulation_data;
  MMC_INIT();omc_alloc_interface.init();
  {
    MMC_TRY_TOP()
  
    MMC_TRY_STACK()
  
    ExternalLibraries_working_setupDataStruc(&simulation_data, threadData);
    res = _main_SimulationRuntime(argc, argv, &simulation_data, threadData);
    
    MMC_ELSE()
    rml_execution_failed();
    fprintf(stderr, "Stack overflow detected and was not caught.\nSend us a bug report at https://trac.openmodelica.org/OpenModelica/newticket\n    Include the following trace:\n");
    printStacktraceMessages();
    fflush(NULL);
    return 1;
    MMC_CATCH_STACK()
    
    MMC_CATCH_TOP(return rml_execution_failed());
  }

  fflush(NULL);
  EXIT(res);
  return res;
}

