/* DSblock model generated by Dymola from Modelica model ConstantWrapper
 Dymola Version 2017 (32-bit), 2016-04-12 translated this at Thu Jul 21 15:06:36 2016

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
#include "storeInput.c"
DYMOLA_STATIC double   SimpleC_M(double  iDouble0_0, const char*  directPath0_0);
/* Codes used in model */

/* Flattened Modelica model:

function SimpleC
discrete input Real iDouble;
input String directPath;
discrete output Real returnDouble(start = iDouble);

external "C" store(iDouble);
annotation(Include="#include \"storeInput.c\"");
end SimpleC;

  */
DYMOLA_STATIC double   SimpleC_M(double  iDouble0_0, const char*  directPath0_0)
   {
  PushContext("SimpleC")
  {
    /* Declare outputs and temporaries */
    double   returnDouble0_0;
    returnDouble0_0 = iDouble0_0;
    /* Start of real code */
    {
      (store)(iDouble0_0);
      }
    /* Output section */
    PopContext()
    return returnDouble0_0;
  }}
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    1
#define NP_    1
#define NPS_   0
#define MAXAuxStr_   1
#define MAXAuxStrLen_   500
#define NHash1_ -1341677511
#define NHash2_ 150256494
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    2
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="ConstantWrapper";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
DYNSetAuxString(did_, "C:\\Users\\justin.shultz\\Dropbox\\FMU\\Passing_Data_Testing\\",
   0);
BoundParameterSection
DYNX(W_,0) = (PushModelContext(1,"SimpleC(const.k, \"C:\\\\Users\\\\justin.shultz\\\\Dropbox\\\\FMU\\\\Passing_Data_Testing\\\\\")")
  SimpleC_M(DYNX(DP_,0), "C:\\Users\\justin.shultz\\Dropbox\\FMU\\Passing_Data_Testing\\"));
PopModelContext();
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareAlias2("simpleCWrapper1.SimpleDouble", "", "const.k", 1, 7, 0, 0)
DeclareVariable("simpleCWrapper1.returnedDouble", "", 0.0, 0.0,0.0,0.0,0,513)
DeclareParameter("const.k", "Constant output value", 0, 25, 0.0,0.0,0.0,0,560)
DeclareAlias2("const.y", "Connector of Real output signal", "const.k", 1, 7, 0, 0)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock
