/* DSblock model generated by Dymola from Modelica model CallDirect
 Dymola Version 2017 (32-bit), 2016-04-12 translated this at Wed Aug 17 17:14:46 2016

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */

                  double CAdd(double x, double y){
                  double answer;
                  answer = x + y;
                  return answer;
                  }
            
DYMOLA_STATIC double   CallDirect_CallAddFunc_M(double  x0_0, double  y0_0);
/* Codes used in model */

/* Flattened Modelica model:

function CallDirect.CallAddFunc
discrete input Real x;
discrete input Real y;
discrete output Real z;

external "C" z = CallAddFunc(x, y);
annotation(Include="
                  double CAdd(double x, double y){
                  double answer;
                  answer = x + y;
                  return answer;
                  }
            ");
end CallDirect.CallAddFunc;

  */
DYMOLA_STATIC double   CallDirect_CallAddFunc_M(double  x0_0, double  y0_0) {
  PushContext("CallDirect.CallAddFunc")
  {
    /* Declare outputs and temporaries */
    double   z0_0;
    z0_0=0;
    /* Start of real code */
    {
      z0_0 = (CallAddFunc)(x0_0, y0_0);
      }
    /* Output section */
    PopContext()
    return z0_0;
  }}
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    2
#define NY_    1
#define NW_    0
#define NP_    0
#define NPS_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 0
#define NHash2_ 0
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="CallDirect";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_
#define DIRECT_FEED_THROUGH 1

TranslatedEquations

BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection
DYNX(Y_,0) = (PushModelContext(1,"CallDirect.CallAddFunc(FirstInput, SecondInput)")
  CallDirect_CallAddFunc_M(DYNX(U_,0), DYNX(U_,1)));
PopModelContext();

DynamicsSection

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareInput("FirstInput", "[:#(prefix=input)]", 0, 0, 0.0,0.0,0.0,0,512)
DeclareInput("SecondInput", "[:#(prefix=input)]", 1, 0, 0.0,0.0,0.0,0,512)
DeclareOutput("FMUOutput", "", 0, 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock
