/* DSblock model generated by Dymola from Modelica model SineWrapper
 Dymola Version 2017 (32-bit), 2016-04-12 translated this at Thu Jun 30 11:31:01 2016

   */

#include <matrixop.h>
/* Declaration of C-structs */
/* Prototypes for functions used in model */
#include "storeInput.c"
DYMOLA_STATIC double   SimpleC_M(double  iDouble0_0, const char*  directPath0_0);
/* Codes used in model */

/* Flattened Modelica model:

function SimpleC
discrete input Real iDouble;
input String directPath;
discrete output Real returnDouble(start = iDouble);

external "C" store(iDouble);
annotation(Include="#include \"storeInput.c\"");
end SimpleC;

  */
DYMOLA_STATIC double   SimpleC_M(double  iDouble0_0, const char*  directPath0_0)
   {
  PushContext("SimpleC")
  {
    /* Declare outputs and temporaries */
    double   returnDouble0_0;
    returnDouble0_0 = iDouble0_0;
    /* Start of real code */
    {
      (store)(iDouble0_0);
      }
    /* Output section */
    PopContext()
    return returnDouble0_0;
  }}
/* DSblock C-code: */

#define NX_    0
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    2
#define NP_    5
#define NPS_   0
#define MAXAuxStr_   1
#define MAXAuxStrLen_   500
#define NHash1_ 514125315
#define NHash2_ -401829497
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  1
#define NSamp_ 0
#define NCons_ 0
#define NA_    1
#define SizePre_ 0
#define SizeEq_ 0
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="SineWrapper";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=0;
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations

InitialSection
DYNSetAuxString(did_, "C:\\Users\\justin.shultz\\Dropbox\\FMU\\Passing_Data_Testing\\",
   0);
BoundParameterSection
InitialSection
InitialSection
InitialStartSection
InitialSection
DefaultSection
InitializeData(0)
InitialSection
InitialSection2
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection

AcceptedSection1

AcceptedSection2
DYNX(W_,0) = DYNX(DP_,3)+(IF LessTime(DYNX(DP_,4), 0) THEN 0 ELSE DYNX(DP_,0)*
  sin(6.283185307179586*DYNX(DP_,1)*(DYNTime-DYNX(DP_,4))+DYNX(DP_,2)));
DYNX(W_,1) = (PushModelContext(1,"SimpleC(simpleCWrapper1.SimpleDouble, \"C:\\\\Users\\\\justin.shultz\\\\Dropbox\\\\FMU\\\\Passing_Data_Testing\\\\\")")
  SimpleC_M(DYNX(W_,0), "C:\\Users\\justin.shultz\\Dropbox\\FMU\\Passing_Data_Testing\\"));
PopModelContext();

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareVariable("simpleCWrapper1.SimpleDouble", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("simpleCWrapper1.returnedDouble", "", 0.0, 0.0,0.0,0.0,0,512)
DeclareParameter("sine1.amplitude", "Amplitude of sine wave", 0, 1, 0.0,0.0,0.0,\
0,560)
DeclareParameter("sine1.freqHz", "Frequency of sine wave [Hz]", 1, 1, 0.0,0.0,\
0.0,0,560)
DeclareParameter("sine1.phase", "Phase of sine wave [rad|deg]", 2, 0, 0.0,0.0,\
0.0,0,560)
DeclareParameter("sine1.offset", "Offset of output signal", 3, 0, 0.0,0.0,0.0,0,560)
DeclareParameter("sine1.startTime", "Output = offset for time < startTime [s]", 4,\
 0, 0.0,0.0,0.0,0,560)
DeclareAlias2("sine1.y", "Connector of Real output signal", "simpleCWrapper1.SimpleDouble", 1,\
 5, 0, 0)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_) {
static Real initStore[1];
}
StartDataBlock
EndDataBlock
