/* Main Simulation File */
/* Simulation code for StoreData_Trial1 generated by the OpenModelica Compiler v1.9.3. */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "StoreData_Trial1_functions.h"
#include "StoreData_Trial1_model.h"
#include "StoreData_Trial1_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define prefixedName_performSimulation StoreData_Trial1_performSimulation
#define prefixedName_updateContinuousSystem StoreData_Trial1_updateContinuousSystem
#include <simulation/solver/perform_simulation.c>

#define prefixedName_performQSSSimulation StoreData_Trial1_performQSSSimulation
#include <simulation/solver/perform_qss_simulation.c>

/* dummy VARINFO and FILEINFO */
const FILE_INFO dummyFILE_INFO = omc_dummyFileInfo;
const VAR_INFO dummyVAR_INFO = omc_dummyVarInfo;
#if defined(__cplusplus)
extern "C" {
#endif
int measure_time_flag = 0;

int StoreData_Trial1_input_function(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}

int StoreData_Trial1_input_function_init(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}


int StoreData_Trial1_output_function(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}


/*
 equation index: 3
 type: SIMPLE_ASSIGN
 der(x) = -StoreData_Trial1.storeData(x)
 */
void StoreData_Trial1_eqFunction_3(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,3};
  $P$DER$Px = (-omc_StoreData__Trial1_storeData(threadData, $Px));
  TRACE_POP
}


int StoreData_Trial1_functionDAE(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH
  int equationIndexes[1] = {0};
  
  data->simulationInfo.needToIterate = 0;
  data->simulationInfo.discreteCall = 1;
  StoreData_Trial1_eqFunction_3(data, threadData);
  data->simulationInfo.discreteCall = 0;
  
  TRACE_POP
  return 0;
}

int StoreData_Trial1_symEulerUpdate(DATA *data, modelica_real dt)
{
  TRACE_PUSH
  #ifdef $P__OMC_DT
    $P__OMC_DT = dt;
  #else
    return -1;
  #endif
  
  TRACE_POP
  return 0;
}



/* forwarded equations */
extern void StoreData_Trial1_eqFunction_3(DATA* data, threadData_t *threadData);

static void functionODE_system0(DATA *data, threadData_t *threadData)
{
  StoreData_Trial1_eqFunction_3(data, threadData);
}

int StoreData_Trial1_functionODE(DATA *data, threadData_t *threadData)
{
  TRACE_PUSH

  
  data->simulationInfo.callStatistics.functionODE++;
  
  functionODE_system0(data, threadData);

  
  TRACE_POP
  return 0;
}

/* forward the main in the simulation runtime */
extern int _main_SimulationRuntime(int argc, char**argv, DATA *data, threadData_t *threadData);

#include "StoreData_Trial1_12jac.h"
#include "StoreData_Trial1_13opt.h"

struct OpenModelicaGeneratedFunctionCallbacks StoreData_Trial1_callback = {
   (int (*)(DATA *, threadData_t *, void *)) StoreData_Trial1_performSimulation,
   (int (*)(DATA *, threadData_t *, void *)) StoreData_Trial1_performQSSSimulation,
   StoreData_Trial1_updateContinuousSystem,
   StoreData_Trial1_callExternalObjectConstructors,
   StoreData_Trial1_callExternalObjectDestructors,
   StoreData_Trial1_initialNonLinearSystem,
   StoreData_Trial1_initialLinearSystem,
   StoreData_Trial1_initialMixedSystem,
   StoreData_Trial1_initializeStateSets,
   StoreData_Trial1_functionODE,
   StoreData_Trial1_functionAlgebraics,
   StoreData_Trial1_functionDAE,
   StoreData_Trial1_input_function,
   StoreData_Trial1_input_function_init,
   StoreData_Trial1_output_function,
   StoreData_Trial1_function_storeDelayed,
   StoreData_Trial1_updateBoundVariableAttributes,
   0 /* useHomotopy */,
   StoreData_Trial1_functionInitialEquations,
   StoreData_Trial1_functionRemovedInitialEquations,
   StoreData_Trial1_updateBoundParameters,
   StoreData_Trial1_checkForAsserts,
   StoreData_Trial1_function_ZeroCrossingsEquations,
   StoreData_Trial1_function_ZeroCrossings,
   StoreData_Trial1_function_updateRelations,
   StoreData_Trial1_checkForDiscreteChanges,
   StoreData_Trial1_zeroCrossingDescription,
   StoreData_Trial1_relationDescription,
   StoreData_Trial1_function_initSample,
   StoreData_Trial1_INDEX_JAC_A,
   StoreData_Trial1_INDEX_JAC_B,
   StoreData_Trial1_INDEX_JAC_C,
   StoreData_Trial1_INDEX_JAC_D,
   StoreData_Trial1_initialAnalyticJacobianA,
   StoreData_Trial1_initialAnalyticJacobianB,
   StoreData_Trial1_initialAnalyticJacobianC,
   StoreData_Trial1_initialAnalyticJacobianD,
   StoreData_Trial1_functionJacA_column,
   StoreData_Trial1_functionJacB_column,
   StoreData_Trial1_functionJacC_column,
   StoreData_Trial1_functionJacD_column,
   StoreData_Trial1_linear_model_frame,
   StoreData_Trial1_mayer,
   StoreData_Trial1_lagrange,
   StoreData_Trial1_pickUpBoundsForInputsInOptimization,
   StoreData_Trial1_setInputData,
   StoreData_Trial1_getTimeGrid,
   StoreData_Trial1_symEulerUpdate,
   StoreData_Trial1_function_initSynchronous,
   StoreData_Trial1_function_updateSynchronous,
   StoreData_Trial1_function_equationsSynchronous

};

void StoreData_Trial1_setupDataStruc(DATA *data, threadData_t *threadData)
{
  assertStreamPrint(threadData,0!=data, "Error while initialize Data");
  data->callback = &StoreData_Trial1_callback;
  data->modelData.modelName = "StoreData_Trial1";
  data->modelData.modelFilePrefix = "StoreData_Trial1";
  data->modelData.resultFileName = NULL;
  data->modelData.modelDir = "C:/Users/fishes3/Dropbox/FMU/Passing_Data_Testing/SimpleStoring";
  data->modelData.modelGUID = "{8c4e810f-3df3-4a00-8276-176fa3c9f9e0}";
  #ifdef OPENMODELICA_XML_FROM_FILE_AT_RUNTIME
  data->modelData.initXMLData = NULL;
  data->modelData.modelDataXml.infoXMLData = NULL;
  #else
  data->modelData.initXMLData =
  #include "StoreData_Trial1_init.c"
  ;
  data->modelData.modelDataXml.infoXMLData =
  #include "StoreData_Trial1_info.c"
  ;
  #endif
  
  data->modelData.nStates = 1;
  data->modelData.nVariablesReal = 2*1+0+0+0 + 0;
  data->modelData.nDiscreteReal = 0;
  data->modelData.nVariablesInteger = 0;
  data->modelData.nVariablesBoolean = 0;
  data->modelData.nVariablesString = 0;
  data->modelData.nParametersReal = 0;
  data->modelData.nParametersInteger = 0;
  data->modelData.nParametersBoolean = 0;
  data->modelData.nParametersString = 0;
  data->modelData.nInputVars = 0;
  data->modelData.nOutputVars = 0;
  
  data->modelData.nAliasReal = 0;
  data->modelData.nAliasInteger = 0;
  data->modelData.nAliasBoolean = 0;
  data->modelData.nAliasString = 0;
  
  data->modelData.nZeroCrossings = 0;
  data->modelData.nSamples = 0;
  data->modelData.nRelations = 0;
  data->modelData.nMathEvents = 0;
  data->modelData.nExtObjs = 0;
  setupModelInfoFunctions(1);
  data->modelData.modelDataXml.fileName = "StoreData_Trial1_info.json";
  data->modelData.modelDataXml.modelInfoXmlLength = 0;
  data->modelData.modelDataXml.nFunctions = 1;
  data->modelData.modelDataXml.nProfileBlocks = 0;
  data->modelData.modelDataXml.nEquations = 4;
  data->modelData.nMixedSystems = 0;
  data->modelData.nLinearSystems = 0;
  data->modelData.nNonLinearSystems = 0;
  data->modelData.nStateSets = 0;
  data->modelData.nJacobians = 4;
  data->modelData.nOptimizeConstraints = 0;
  data->modelData.nOptimizeFinalConstraints = 0;
  
  data->modelData.nDelayExpressions = 0;
  
  data->modelData.nClocks = 0;
  data->modelData.nSubClocks = 0;
  
}

#ifdef __cplusplus
}
#endif

static int rml_execution_failed()
{
  fflush(NULL);
  fprintf(stderr, "Execution failed!\n");
  fflush(NULL);
  return 1;
}

#if defined(threadData)
#undef threadData
#endif
/* call the simulation runtime main from our main! */
int main(int argc, char**argv)
{
  int res;
  DATA simulation_data;
  MMC_INIT();omc_alloc_interface.init();
  {
    MMC_TRY_TOP()
  
    MMC_TRY_STACK()
  
    StoreData_Trial1_setupDataStruc(&simulation_data, threadData);
    res = _main_SimulationRuntime(argc, argv, &simulation_data, threadData);
    
    MMC_ELSE()
    rml_execution_failed();
    fprintf(stderr, "Stack overflow detected and was not caught.\nSend us a bug report at https://trac.openmodelica.org/OpenModelica/newticket\n    Include the following trace:\n");
    printStacktraceMessages();
    fflush(NULL);
    return 1;
    MMC_CATCH_STACK()
    
    MMC_CATCH_TOP(return rml_execution_failed());
  }

  fflush(NULL);
  EXIT(res);
  return res;
}

