/* Additional record code for StoreData_Trial1 generated by the OpenModelica Compiler v1.9.3. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

